/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ITTeam;

import Business.Activity.Activity;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Session.SessionLog;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class ITTeamWorkAreaJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private UserAccount userAccount;
private Organization organization;
private Enterprise enterprise;
private SessionLog session;
private Employee employee;
    /**
     * Creates new form ITTeamWorkAreaJPanel
     */
    public ITTeamWorkAreaJPanel(JPanel upc,UserAccount ua,Organization org,Enterprise ent,SessionLog s) {
        initComponents();
        this.userProcessContainer=upc;
        this.userAccount=ua;
        this.organization=org;
        this.enterprise=ent;
        this.session= s;
        Activity a= session.getActivityDirectory().addActivity();
     a.setActivityTime(new Date());
     a.setjPanelName("ITWorkAreaJPanel");
         for (Employee e : organization.getEmployeeDirectory().getEmployeeList()) {
            if (ua.getEmployee().getName().equals(e.getName())) {
                employee = e;
                lblEmployeeName.setText(employee.getName());
                return;
            }
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnViewDatabase = new javax.swing.JButton();
        btnActivityLog = new javax.swing.JButton();
        btnCustomerCareRequests = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("/siddharth/Info 5100/Project/src/UserInterface/Screen Shot 2016-03-30 at 11.20.59 AM.png")); // NOI18N

        lblEmployeeName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblEmployeeName.setForeground(new java.awt.Color(0, 102, 255));
        lblEmployeeName.setText("Employee Name");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("is Logged in!");

        btnViewDatabase.setForeground(new java.awt.Color(51, 102, 255));
        btnViewDatabase.setText("View Database Information");
        btnViewDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDatabaseActionPerformed(evt);
            }
        });

        btnActivityLog.setForeground(new java.awt.Color(51, 102, 255));
        btnActivityLog.setText("View Activity Log");
        btnActivityLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivityLogActionPerformed(evt);
            }
        });

        btnCustomerCareRequests.setForeground(new java.awt.Color(51, 102, 255));
        btnCustomerCareRequests.setText("View Requests");
        btnCustomerCareRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerCareRequestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCustomerCareRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActivityLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployeeName))
                .addGap(55, 55, 55)
                .addComponent(btnViewDatabase)
                .addGap(18, 18, 18)
                .addComponent(btnActivityLog)
                .addGap(32, 32, 32)
                .addComponent(btnCustomerCareRequests)
                .addContainerGap(230, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDatabaseActionPerformed
        // TODO add your handling code here:
        DatabaseInformationJPanel panel = new DatabaseInformationJPanel(userProcessContainer,userAccount,organization,enterprise,session);
        userProcessContainer.add("DatabaseInformationJPanel",panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDatabaseActionPerformed

    private void btnActivityLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivityLogActionPerformed
        // TODO add your handling code here:
        ViewActivityLogJPanel panel = new ViewActivityLogJPanel(userProcessContainer,userAccount,organization,enterprise,session);
        userProcessContainer.add("ViewActivityLogJPanel",panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnActivityLogActionPerformed

    private void btnCustomerCareRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerCareRequestsActionPerformed
        // TODO add your handling code here:
        CustomerCareRequestJPanel panel =new CustomerCareRequestJPanel(userProcessContainer,userAccount,organization,enterprise,session);
        userProcessContainer.add("CustomerCareRequestJPanel",panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCustomerCareRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivityLog;
    private javax.swing.JButton btnCustomerCareRequests;
    private javax.swing.JButton btnViewDatabase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmployeeName;
    // End of variables declaration//GEN-END:variables
}
