/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ITTeam;

import Business.Activity.Activity;
import Business.Customer.Customer;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Session.SessionLog;
import Business.UserAccount.UserAccount;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ViewActivityLogJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private UserAccount userAccount;
private Organization organization;
private Enterprise enterprise;
private SessionLog session;
    /**
     * Creates new form ViewActivityLogJPanel
     */
    public ViewActivityLogJPanel(JPanel upc,UserAccount ua,Organization org,Enterprise ent,SessionLog s) {
        initComponents();
        this.userProcessContainer=upc;
        this.userAccount=ua;
        this.organization=org;
        this.enterprise=ent;
        this.session = s;
            Activity a= session.getActivityDirectory().addActivity();
     a.setActivityTime(new Date());
     a.setjPanelName("ViewActivityLogJPanel");
     populateTable();
    }
public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblSessionLogDetails.getModel();
        dtm.setNumRows(0);

        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
              
                for (SessionLog sl : ua.getSessionDirectory().getSessionList()) {
                    Object row[] = new Object[5];
                    row[0] = sl;
                    row[1] = sl.getEndTime();
                    if (null == ua.getEmployee()) {
                        row[2] = ua.getCustomer().getName();
                    } else {
                        row[2] = ua.getEmployee().getName();
                    }
                    row[3] = ua.getUserId();
                    row[4] = ua.getRole();
                    dtm.addRow(row);
                }
            }
            
        }
    }
public void populateSessionActivities(SessionLog s) {
        DefaultTableModel dtm = (DefaultTableModel) tblSessionActivities.getModel();
        dtm.setRowCount(0);

        for (Activity a : s.getActivityDirectory().getActivityList()) {
            Object row[] = new Object[2];
            row[0] = a;
            row[1] = a.getjPanelName();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSessionLogDetails = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSessionActivities = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon("/siddharth/Info 5100/Project/src/UserInterface/Screen Shot 2016-03-30 at 11.20.59 AM.png")); // NOI18N

        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("View Activity Log:-");

        tblSessionLogDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Start Time", "End Time", "UserAccount Name", "UserId", "Role"
            }
        ));
        jScrollPane1.setViewportView(tblSessionLogDetails);

        tblSessionActivities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Activity Time", "Panel Name"
            }
        ));
        jScrollPane2.setViewportView(tblSessionActivities);

        btnViewDetails.setForeground(new java.awt.Color(51, 102, 255));
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(461, 461, 461))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnViewDetails)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblSessionLogDetails.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a customer  from the table");
            return;
        }
       SessionLog sL = (SessionLog) tblSessionLogDetails.getValueAt(selectedRow, 0);
       
        populateSessionActivities(sL);
    }//GEN-LAST:event_btnViewDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSessionActivities;
    private javax.swing.JTable tblSessionLogDetails;
    // End of variables declaration//GEN-END:variables
}
