/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Email.Email;
import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.MessagingException;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class EmailJPanel extends javax.swing.JPanel {

    private Email email;
    private JPanel userProcessContainer;
    static String attachment_path;
    static String test;

    /**
     * Creates new form EmailJPanel
     */
    public EmailJPanel(JPanel upc) {
        initComponents();
        email = new Email();
        this.userProcessContainer = upc;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTO = new javax.swing.JTextField();
        txtSubject = new javax.swing.JTextField();
        txtAttachment = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnBrowse = new javax.swing.JButton();
        btnSendEmail = new javax.swing.JButton();
        txtAttachmentName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCC = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon("/siddharth/Info 5100/Project/src/UserInterface/Screen Shot 2016-04-11 at 2.35.42 PM.png")); // NOI18N

        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("To");

        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Message");

        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("Subject");

        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("Attachment");

        txtTO.setForeground(new java.awt.Color(0, 102, 255));

        txtSubject.setForeground(new java.awt.Color(0, 102, 255));

        txtAttachment.setForeground(new java.awt.Color(51, 102, 255));

        txtMessage.setColumns(20);
        txtMessage.setForeground(new java.awt.Color(51, 102, 255));
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        btnBrowse.setForeground(new java.awt.Color(51, 102, 255));
        btnBrowse.setIcon(new javax.swing.ImageIcon("/siddharth/Info 5100/Project/src/UserInterface/Screen Shot 2016-04-08 at 6.59.01 PM.png")); // NOI18N
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnSendEmail.setForeground(new java.awt.Color(51, 102, 255));
        btnSendEmail.setIcon(new javax.swing.ImageIcon("/siddharth/Info 5100/Project/src/UserInterface/Screen Shot 2016-04-08 at 7.04.31 PM.png")); // NOI18N
        btnSendEmail.setText("Send");
        btnSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmailActionPerformed(evt);
            }
        });

        txtAttachmentName.setForeground(new java.awt.Color(0, 102, 255));
        txtAttachmentName.setText("Attachment Name");
        txtAttachmentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAttachmentNameActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("CC");

        txtCC.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSendEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAttachmentName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTO, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSubject, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAttachment, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCC, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBrowse)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAttachment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(btnBrowse))))
                .addGap(5, 5, 5)
                .addComponent(txtAttachmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSendEmail)
                .addGap(110, 110, 110))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser jc = new JFileChooser();
        jc.setDialogType(JFileChooser.OPEN_DIALOG);
        jc.showDialog(null, "Mail Send");
        File f = jc.getSelectedFile();
        attachment_path = f.getAbsolutePath();
        txtAttachment.setText(attachment_path);

    }//GEN-LAST:event_btnBrowseActionPerformed
    public  void sendmail(String mailTo, String mailCC, String subject, String content) {

        Properties props = System.getProperties();

        props.setProperty("mail.transport.protocol", "smtp");
        props.setProperty("mail.host", "smtp.mail.yahoo.com");
        props.put("mail.smtp.socketFactory.port", "465");

        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.socketFactory.fallback", "false");
        props.setProperty("mail.smtp.quitwait", "false");
        props.put("mail.smtp.port", "465");

        try {
            Session session = Session.getDefaultInstance(props,
                    new Authenticator() {

                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(
                            "testbank54@yahoo.com", "santoshwale");
                }
            });
            Message message = new MimeMessage(session);
            Address bankEmailId = new InternetAddress("testbank54@yahoo.com");
            Address toAddress = new InternetAddress(mailTo);
            Address ccAddress = new InternetAddress(mailCC);

            message.setFrom(bankEmailId);
            message.setRecipient(Message.RecipientType.TO, toAddress);
            message.setRecipient(Message.RecipientType.CC, ccAddress);
            message.setSubject(subject);

            MimeBodyPart msgBody = new MimeBodyPart();
            MimeMultipart multipart = new MimeMultipart();

            //multipart.addBodyPart(msgBody);

            msgBody.setText(content, "utf-8");
            msgBody.setHeader("Content-Type", "text/html; charset=\"utf-8\"");
            msgBody.setHeader("Content-Transfer-Encoding", "quoted-printable");

            message.setContent(multipart);
            message.setSentDate(new Date());

            multipart.addBodyPart(msgBody);
            msgBody = new MimeBodyPart();
            javax.activation.DataSource source = new FileDataSource(attachment_path);
            msgBody.setDataHandler(new DataHandler(source));
            test = txtAttachmentName.getText();
            msgBody.setFileName(test);
            multipart.addBodyPart(msgBody);
            message.setContent(multipart);
            Transport.send(message);

            JOptionPane.showMessageDialog(null, "Message Sent");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmailActionPerformed
        // TODO add your handling code here:
        sendmail(txtTO.getText(), txtCC.getText(), txtSubject.getText(), txtMessage.getText());

    }//GEN-LAST:event_btnSendEmailActionPerformed

    private void txtAttachmentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAttachmentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttachmentNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSendEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAttachment;
    private javax.swing.JTextField txtAttachmentName;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTO;
    // End of variables declaration//GEN-END:variables
}
