/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class TermsandConditionJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;

   private Business business;
    /**
     * Creates new form NewUserJPanel
     */
    public TermsandConditionJPanel(JPanel upc,Business b) {
        initComponents();
        this.userProcessContainer = upc;
        this.business=b;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnIDisagree = new javax.swing.JButton();
        btnIAgree = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        backJButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Terms & Conditions:-");

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 102, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("1.Account Opening Form” (AOF) refers to the relationship form for Savings Account.\n2.\"Customer\" refers to any person holding an Account with Bank of Boston.\n3.“Quarter” shall mean a financial quarter i.e. April – June, July – September, October – \n     December, January – March in any financial year.\n4.\"Services\" shall mean the services provided by Bank of Boston in connection with the Saving \n    Account and more particularly described in these Terms.\n5.\"Bank of Boston Customer Support\" refers to Bank of Boston - It is a service provided to \n    customer for any assistance.\n\nOperating Accounts:-\n1.An Account may be opened in the names of : An individual in his/her own name.\n2.All the Accounts maintained in the name of an individual shall be operated singly by the \n   individual or the Power of Attorney holder of such individual\n3.The Customer shall open the Account with a minimum balance as prescribed by Bank of Boston.\n\nChange of Terms :\n\nBank of Boston shall have the absolute discretion to amend or supplement any of the Terms\nat any time.\n\nNotices :\n\nNotices in respect of the Account, the services and facilities in connection with the \nAccount may be given by ICICI Bank either through email or posting a letter to the \nCustomer’s address.\n ");
        jScrollPane1.setViewportView(jTextArea1);

        btnIDisagree.setForeground(new java.awt.Color(0, 102, 204));
        btnIDisagree.setText("I Disagree");
        btnIDisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDisagreeActionPerformed(evt);
            }
        });

        btnIAgree.setForeground(new java.awt.Color(0, 102, 204));
        btnIAgree.setText("I Agree");
        btnIAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIAgreeActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("/siddharth/Info 5100/Project/src/UserInterface/Screen Shot 2016-03-30 at 11.20.59 AM.png")); // NOI18N

        backJButton4.setForeground(new java.awt.Color(51, 102, 255));
        backJButton4.setText("<< Back");
        backJButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton4)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(btnIDisagree)
                        .addGap(189, 189, 189)
                        .addComponent(btnIAgree)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIAgree)
                    .addComponent(btnIDisagree))
                .addGap(28, 28, 28)
                .addComponent(backJButton4)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIAgreeActionPerformed
        // TODO add your handling code here:
        CreateCustomerJPanel panel = new CreateCustomerJPanel(userProcessContainer,business);
        userProcessContainer.add("CreateCustomerPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnIAgreeActionPerformed

    private void btnIDisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDisagreeActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnIDisagreeActionPerformed

    private void backJButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton4ActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton4;
    private javax.swing.JButton btnIAgree;
    private javax.swing.JButton btnIDisagree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
